//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSnowshoes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection userimg_path {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["userimg_path"]));
            }
            set {
                this["userimg_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection username {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection userimgacc_path {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["userimgacc_path"]));
            }
            set {
                this["userimgacc_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection woahThereHello {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["woahThereHello"]));
            }
            set {
                this["woahThereHello"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection notificationapps {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["notificationapps"]));
            }
            set {
                this["notificationapps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string notificationtext {
            get {
                return ((string)(this["notificationtext"]));
            }
            set {
                this["notificationtext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection snowshoesapps {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["snowshoesapps"]));
            }
            set {
                this["snowshoesapps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection windowsapps {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["windowsapps"]));
            }
            set {
                this["windowsapps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection nickname {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["nickname"]));
            }
            set {
                this["nickname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection space_back_path {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["space_back_path"]));
            }
            set {
                this["space_back_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection custColor {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["custColor"]));
            }
            set {
                this["custColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection loggedIn {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["loggedIn"]));
            }
            set {
                this["loggedIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool runTimes {
            get {
                return ((bool)(this["runTimes"]));
            }
            set {
                this["runTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection lock_path {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lock_path"]));
            }
            set {
                this["lock_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int whoIsThisCrazyDoge {
            get {
                return ((int)(this["whoIsThisCrazyDoge"]));
            }
            set {
                this["whoIsThisCrazyDoge"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Chrome</string>
  <string>Word</string>
  <string>PowerPoint</string>
  <string>Excel</string>
  <string>OneNote</string>
  <string>Spotify</string>
  <string>Turntable</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection appListIco {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["appListIco"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection emailList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["emailList"]));
            }
            set {
                this["emailList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection fontsOfScience {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["fontsOfScience"]));
            }
            set {
                this["fontsOfScience"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection darkerFontsOfScience {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["darkerFontsOfScience"]));
            }
            set {
                this["darkerFontsOfScience"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stayHere {
            get {
                return ((bool)(this["stayHere"]));
            }
            set {
                this["stayHere"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Jack Altman</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection youAreTheSpecial {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["youAreTheSpecial"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>IndigoBox Studios</string>
  <string>Erfiden</string>
  <string>Document1204</string>
  <string>Tech Squared</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection youAreTheSpecialOrganization {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["youAreTheSpecialOrganization"]));
            }
            set {
                this["youAreTheSpecialOrganization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>AliceBlue</string>\r\n  <string>AntiqueWhite</string>\r\n  <string>Aqua</strin" +
            "g>\r\n  <string>Aquamarine</string>\r\n  <string>Azure</string>\r\n  <string>Beige</st" +
            "ring>\r\n  <string>Bisque</string>\r\n  <string>Black</string>\r\n  <string>BlanchedAl" +
            "mond</string>\r\n  <string>Blue</string>\r\n  <string>BlueViolet</string>\r\n  <string" +
            ">Brown</string>\r\n  <string>BurlyWood</string>\r\n  <string>CadetBlue</string>\r\n  <" +
            "string>Chartreuse</string>\r\n  <string>Chocolate</string>\r\n  <string>Coral</strin" +
            "g>\r\n  <string>CornflowerBlue</string>\r\n  <string>Cornsilk</string>\r\n  <string>Cr" +
            "imson</string>\r\n  <string>Cyan</string>\r\n  <string>DarkBlue</string>\r\n  <string>" +
            "DarkCyan</string>\r\n  <string>DarkGoldenrod</string>\r\n  <string>DarkGray</string>" +
            "\r\n  <string>DarkGreen</string>\r\n  <string>DarkKhaki</string>\r\n  <string>DarkMage" +
            "nta</string>\r\n  <string>DarkOliveGreen</string>\r\n  <string>DarkOrange</string>\r\n" +
            "  <string>DarkOrchid</string>\r\n  <string>DarkRed</string>\r\n  <string>DarkSalmon<" +
            "/string>\r\n  <string>DarkSeaGreen</string>\r\n  <string>DarkSlateBlue</string>\r\n  <" +
            "string>DarkSlateGray</string>\r\n  <string>DarkTurquoise</string>\r\n  <string>DarkV" +
            "iolet</string>\r\n  <string>DeepPink</string>\r\n  <string>DeepSkyBlue</string>\r\n  <" +
            "string>DimGray</string>\r\n  <string>DodgerBlue</string>\r\n  <string>Firebrick</str" +
            "ing>\r\n  <string>FloralWhite</string>\r\n  <string>ForestGreen</string>\r\n  <string>" +
            "Fuchsia</string>\r\n  <string>Gainsboro</string>\r\n  <string>GhostWhite</string>\r\n " +
            " <string>Gold</string>\r\n  <string>Goldenrod</string>\r\n  <string>Gray</string>\r\n " +
            " <string>Green</string>\r\n  <string>GreenYellow</string>\r\n  <string>Honeydew</str" +
            "ing>\r\n  <string>HotPink</string>\r\n  <string>IndianRed</string>\r\n  <string>Indigo" +
            "</string>\r\n  <string>Ivory</string>\r\n  <string>Khaki</string>\r\n  <string>Lavende" +
            "r</string>\r\n  <string>LavenderBlush</string>\r\n  <string>LawnGreen</string>\r\n  <s" +
            "tring>LemonChiffon</string>\r\n  <string>LightBlue</string>\r\n  <string>LightCoral<" +
            "/string>\r\n  <string>LightCyan</string>\r\n  <string>LightGoldenrodYellow</string>\r" +
            "\n  <string>LightGray</string>\r\n  <string>LightGreen</string>\r\n  <string>LightPin" +
            "k</string>\r\n  <string>LightSalmon</string>\r\n  <string>LightSeaGreen</string>\r\n  " +
            "<string>LightSkyBlue</string>\r\n  <string>LightSlateGray</string>\r\n  <string>Ligh" +
            "tSteelBlue</string>\r\n  <string>LightYellow</string>\r\n  <string>Lime</string>\r\n  " +
            "<string>LimeGreen</string>\r\n  <string>Linen</string>\r\n  <string>Magenta</string>" +
            "\r\n  <string>Maroon</string>\r\n  <string>MediumAquamarine</string>\r\n  <string>Medi" +
            "umBlue</string>\r\n  <string>MediumOrchid</string>\r\n  <string>MediumPurple</string" +
            ">\r\n  <string>MediumSeaGreen</string>\r\n  <string>MediumSlateBlue</string>\r\n  <str" +
            "ing>MediumSpringGreen</string>\r\n  <string>MediumTurquoise</string>\r\n  <string>Me" +
            "diumVioletRed</string>\r\n  <string>MidnightBlue</string>\r\n  <string>MintCream</st" +
            "ring>\r\n  <string>MistyRose</string>\r\n  <string>Moccasin</string>\r\n  <string>Nava" +
            "joWhite</string>\r\n  <string>Navy</string>\r\n  <string>OldLace</string>\r\n  <string" +
            ">Olive</string>\r\n  <string>OliveDrab</string>\r\n  <string>Orange</string>\r\n  <str" +
            "ing>OrangeRed</string>\r\n  <string>Orchid</string>\r\n  <string>PaleGoldenrod</stri" +
            "ng>\r\n  <string>PaleGreen</string>\r\n  <string>PaleTurquoise</string>\r\n  <string>P" +
            "aleVioletRed</string>\r\n  <string>PapayaWhip</string>\r\n  <string>PeachPuff</strin" +
            "g>\r\n  <string>Peru</string>\r\n  <string>Pink</string>\r\n  <string>Plum</string>\r\n " +
            " <string>PowderBlue</string>\r\n  <string>Purple</string>\r\n  <string>Red</string>\r" +
            "\n  <string>RosyBrown</string>\r\n  <string>RoyalBlue</string>\r\n  <string>SaddleBro" +
            "wn</string>\r\n  <string>Salmon</string>\r\n  <string>SandyBrown</string>\r\n  <string" +
            ">SeaGreen</string>\r\n  <string>SeaShell</string>\r\n  <string>Sienna</string>\r\n  <s" +
            "tring>Silver</string>\r\n  <string>SkyBlue</string>\r\n  <string>SlateBlue</string>\r" +
            "\n  <string>SlateGray</string>\r\n  <string>Snow</string>\r\n  <string>SpringGreen</s" +
            "tring>\r\n  <string>SteelBlue</string>\r\n  <string>Tan</string>\r\n  <string>Teal</st" +
            "ring>\r\n  <string>Thistle</string>\r\n  <string>Tomato</string>\r\n  <string>Turquois" +
            "e</string>\r\n  <string>Violet</string>\r\n  <string>Wheat</string>\r\n  <string>White" +
            "</string>\r\n  <string>WhiteSmoke</string>\r\n  <string>Yellow</string>\r\n  <string>Y" +
            "ellowGreen</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection allThePrettyColorsHere {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["allThePrettyColorsHere"]));
            }
            set {
                this["allThePrettyColorsHere"] = value;
            }
        }
    }
}
